# Pandas crash course


<img align="center" src="https://github.com/dfbarrero/dataCourse/raw/master/pandas/figs/pandas.png" width="300">



### Library imports

In [1]:
import pandas as pd

In [2]:
import numpy as np # Pandas and NumPy use to be together

## The Series object

In [3]:
series = pd.Series([0.25, 0.5, 0.75, 1.0])

print(series)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
series[1:3]

1    0.50
2    0.75
dtype: float64

In [5]:
series = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

series

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

| Index       | Values |
|-----|-----------|
| 'a' | 0.25  |
| 'b' | 0.5   |
| 'c' | 0.75  |
| 'c' | 1  |

In [6]:
series.values

array([0.25, 0.5 , 0.75, 1.  ])

In [7]:
series.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
series[0] # Deprecated

/tmp/ipython-input-4033605060.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series[0] # Deprecated

np.float64(0.25)

In [9]:
series['a']

np.float64(0.25)

In [10]:
series['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [11]:
series[series>0.5]

c    0.75
d    1.00
dtype: float64

In [12]:
series[(series>0.5) & (series<1)]

c    0.75
dtype: float64

## The DataFrame object

Data analysis heavily relies on *dataframes*.

![Dataframe](https://pynative.com/wp-content/uploads/2021/02/dataframe.png)

(Source: https://pynative.com/python-pandas-dataframe/)

In [13]:
df = pd.DataFrame(np.random.rand(3,2), index=['a', 'b', 'c'], columns=['foo', 'bar'])

df

        foo       bar
a  0.720109  0.108615
b  0.149387  0.751458
c  0.238853  0.850830

In [14]:
df.values

array([[0.72010927, 0.10861531],
       [0.14938698, 0.75145763],
       [0.23885301, 0.85083023]])

In [15]:
df.columns

Index(['foo', 'bar'], dtype='object')

In [16]:
df.index

Index(['a', 'b', 'c'], dtype='object')

Indexing refers to columns

In [17]:
df['foo']

a    0.720109
b    0.149387
c    0.238853
Name: foo, dtype: float64

Slicing refers to rows

In [18]:
df['a':'b']

        foo       bar
a  0.720109  0.108615
b  0.149387  0.751458

In [19]:
df['b':]

        foo       bar
b  0.149387  0.751458
c  0.238853  0.850830

Masking refers to rows

In [20]:
df[df['foo'] > 0.5]

        foo       bar
a  0.720109  0.108615

In [21]:
df[df['foo'] < 0.5]

        foo       bar
b  0.149387  0.751458
c  0.238853  0.850830

In [22]:
print(df)

        foo       bar
a  0.720109  0.108615
b  0.149387  0.751458
c  0.238853  0.850830

In [23]:
display(df) # Only in notebooks

        foo       bar
a  0.720109  0.108615
b  0.149387  0.751458
c  0.238853  0.850830

## Loading data

We're going to use the Titanic dataset.

In [25]:
data = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")

In [27]:
pd.read_csv

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'>

Reference documentation: [pd.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).

In [28]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Please, observe that the dataset only defines columns names.

Upload data to Colab (**It won't work anywhere else!**)

In [ ]:
# It only works in Google Colab!!!

from google.colab import files
uploaded = files.upload()

# To store dataset in a Pandas Dataframe
import io
df2 = pd.read_csv(io.BytesIO(uploaded['myfilename.csv']))

## Dataset summaries

In [ ]:
data.shape

In [ ]:
data.shape[0]

In [ ]:
data.shape[1]

In [ ]:
len(data) # Count rows

In [ ]:
data.info()

In [ ]:
data.dtypes

In [ ]:
data.describe()

In [ ]:
data.describe(include="all")

New concept: NaN (*not a number*)

In [ ]:
data['class'].value_counts()

In [ ]:
data['class'].nunique()

## Data selection by column

In [ ]:
data["fare"]

In [ ]:
data.fare

In [ ]:
data[["class", "sex", "fare"]]

## Data selection by row

In [ ]:
data.head()

In [ ]:
data.tail()

In [ ]:
data[data['class'] == "First"];

In [ ]:
data[data['age'] < 30];

In [ ]:
data.drop_duplicates();

In [ ]:
data.nlargest(3, "age")

In [ ]:
data.nsmallest(3, "age")

In [ ]:
data[5, 5] # Error!

## loc, iloc and at indexers

**loc**: Explicit index (i.e., its label)

In [ ]:
data.loc[:, 'age':'fare'].head() # [row, column]

In [ ]:
data.loc[data['age'] < 10, ['class','sex']]

**iloc[]**: Implicit index (i.e., its numeric index)

In [ ]:
data.iloc[3] # Row number 3; one row, so the output changes

In [ ]:
data.iloc[[1, 5, 10]]

In [ ]:
data.iloc[1, 3]

In [ ]:
data.iloc[:, [1,2,6]].head() # Returns columns 1, 2 and 6

In [ ]:
data.iloc[5:10]

*at[]* and *iat[]*: Selecting single elements from a DataFrame.

In [ ]:
data.at[1, "age"]

In [ ]:
data.iat[1, 6]

Complex queries.

In [ ]:
data[(data['age']>10) & (data['age']<15)]

In [ ]:
data.query("(age>10) and (age<15)")

## Missing data

In [ ]:
data.isna().sum()

Observe method chaining in the cell above.

In [ ]:
data['age'].isna().sum()

In [ ]:
data.notnull().sum()

Handling NaNs.

In [ ]:
display(data.head())

data.dropna().head()

In [ ]:
print(f"Rows: {len(data)}")
print(f"Rows: {len(data.dropna())}")

In [ ]:
cleanData = data.fillna("FILLED")

display(data['deck'].head())
display(cleanData['deck'].head())

In [ ]:
cleanData = data.fillna(0)

display(data['deck'].head())
display(cleanData['deck'].head())

## Making new columns

In [ ]:
data['relatives'] = data['sibsp'] + data['parch']

data[data['relatives'] > 1].head()

## Delete rows and columns

In [ ]:
clean = data.drop('relatives', axis=1); # Delete column

print(data.columns)
print(clean.columns)

Pandas use to return a new dataframe or view. This behaviour can be changed with the inplace parameter, as in the following cell:

In [ ]:
data.drop('relatives', axis=1, inplace=True); # Delete column in the same dataframe

print(data.columns)

In [ ]:
data.drop(['sibsp', 'parch'], axis=1); # Delete several columns

In [ ]:
data.drop([10,12,20], axis=0); # Delete several rows

## Combine dataset

In [ ]:
df1 = pd.DataFrame([{'A': 'A0', 'B': 'B0'}, {'A': 'A1', 'B': 'B1'}])
df2 = pd.DataFrame([{'A': 'A2', 'B': 'B2'}, {'A': 'A3', 'B': 'B3'}])

display(df1)
display(df2)

In [ ]:
pd.concat([df1, df2])

In [ ]:
pd.concat([df1, df2], axis=1)

### Renaming columns and indices

In [ ]:
display(df1)

df1.index = ["row1", "row2"]

display(df1)

In [ ]:
df1.columns = ["col1", "col2"]

df1

## Group data

In [ ]:
data.head()

In [ ]:
data.mean(numeric_only=True)

In [ ]:
data.groupby('class').mean()

<img align="center" src="https://github.com/dfbarrero/dataCourse/raw/master/pandas/figs/03.08-split-apply-combine.png" width="500">

In [ ]:
data.groupby("class").mean()['survived']

In [ ]:
data.groupby("class").describe()

In [ ]:
data.groupby("class").describe().T

In [ ]:
for (name, group) in data.groupby('class'):
    print("-----> " + name + " <-----")
    display(group)
    print("\n")

## Iterate over a dataframe

In [ ]:
for key in data.keys():
    print(key)

In [ ]:
for index, row in data.head(3).iterrows():
    print(index)
    print(row)

## Correlations

In [ ]:
data.corr(numeric_only = True)

## Plots

First we must prepare the graphical device.

In [ ]:
%matplotlib inline

We are ready to plot.

In [ ]:
data['fare'].hist()

In [ ]:
data.plot.scatter(x="age", y="fare")

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(data.corr(numeric_only = True), annot=True)

## Exercises

Perform some basic operations on the planets (i.e., exoplanets) toy dataset.

In [ ]:
import seaborn as sns

planets = sns.load_dataset('planets')

1.- Visualize your raw data.

2.- Identify the columns along with its datatype.

3.- Remove any column without interest.

4.- Obtain some summary statistics.

5.- Determine the number of NaNs that your dataset contains.

6.- Remove those rows with NaNs.

7.- Identify the exoplanets detection methods.

8.- Compute the number of planets detected by each method.

9.- Obtain the main statistics (mean, median, standard deviation, maximum and minimum) of the explanets grouped by detection method.

10.- Visualize an histogram of each variable of interest.

11.- For each detection method, visualize an histogram of any column of your interest. Do it placing one histogram in one cell, use as many cells as you need. Take a subset of your dataset in each cell. (Next week we will learn a more convenient way to do it).

12.- Visualize an scatterplot for each pair of attributes of interest. Place each plot in a different cell, using as many cells as you need.